name: video_generation_service

services:
  wan_model:
    build:
      context: .
      dockerfile: dockerfile_model
    container_name: wan_model 
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./lora_fixed:/app/lora
    restart: unless-stopped
    ports:
      - "11222:11222"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command:
      uvicorn main:app --host 0.0.0.0 --port 11222

  api:
    build: ./api
    container_name: wan_api
    ports:
      - "8000:8000"

  ui:
    build: ./ui
    container_name: wan_ui
    environment:
      API_URL: "http://api:8000/generate"
    ports:
      - "7860:7860"
    depends_on:
      - api
